

/*
 * INSERT DE PRODUTOS GENERICOS 
 */

INSERT INTO DBA.PRODUTO(IDPRODUTO, IDSECAO, IDGRUPO,IDSUBGRUPO, DESCRCOMPRODUTO, VALGRAMAENTRADA , VALGRAMASAIDA,
 DTALTERACAO,
 DTALTERACAOEMBALAGEMSAIDA,
 EMBALAGEMENTRADA,
 EMBALAGEMSAIDA,
 FLAGEXPBALANCA,
 IDCSTIPIENTRADA,
IDCSTIPISAIDA,
IDNATUREZAPISCOFINS,
 MODELO,
PERREDUCAOPISCOFINS,
 TIPOBAIXAMESTRE)
SELECT 
	ROW_NUMBER()OVER() AS IDPRODUTO,
	9999 AS IDSECAO,
	9999 AS IDGRUPO,
	9999 AS IDSUBGRUPO,
	'PRODUTO GENERICO' DESCRCOMPRODUTO,
	1 VALGRAMAENTRADA , 
	1 VALGRAMASAIDA,
	DBA.TODAY() DTALTERACAO,
	DBA.TODAY() DTALTERACAOEMBALAGEMSAIDA,
	'UN' EMBALAGEMENTRADA,
	'UN' EMBALAGEMSAIDA,
	'F' FLAGEXPBALANCA,
	50 IDCSTIPIENTRADA,
	1 IDCSTIPISAIDA,
	NULL IDNATUREZAPISCOFINS,
	'' MODELO,
	0 PERREDUCAOPISCOFINS,
	'I' TIPOBAIXAMESTRE
FROM 
 	DBA.CEP_ECT  
FETCH FIRST 500000 ROWS ONLY 

go
INSERT INTO DBA.PRODUTO_GRADE (
	CODBAR,
	CODBARPRODTRIB,
	CODCEST,
	DESCRRESPRODUTO, 
	DTALTERACAO,
	DTCADASTRO,
	IDCODBARPROD,
	IDCODBARPRODTRIB,
	IDPRODUTO, 
	IDSUBPRODUTO,
	NCM,
	SUBDESCRICAO)
SELECT 
	IDPRODUTO + 222222222 	CODBAR,
	IDPRODUTO + 222222222  CODBARPRODTRIB,
	'0000000'	CODCEST,
	'PRODUTO_GENERICO' AS DESCRRESPRODUTO,
	DBA.TODAY() DTALTERACAO,
	DBA.TODAY()  DTCADASTRO,
	IDPRODUTO + 222222222   IDCODBARPROD,
	IDPRODUTO + 222222222   IDCODBARPRODTRIB,
	P.IDPRODUTO AS IDPRODUTO,
	P.IDPRODUTO AS IDSUBPRODUTO,
	'00000000'NCM,
	'' SUBDESCRICAO
FROM 
	DBA.PRODUTO P
WHERE 
	NOT EXISTS (SELECT 1 FROM DBA.PRODUTO_GRADE B WHERE B.IDPRODUTO = P.IDPRODUTO)
GO
COMMIT

SELECT *
FROM CONV.teste 

DROP TABLE CONV.teste



-------------------------------------
-- LIMPA AMBIENTE 
-------------------------------------

DELETE FROM DBA.ESTOQUE_BALANCO 
GO



CREATE TABLE CONV.TESTE
(
  Step_Timestamp			TIMESTAMP DEFAULT CURRENT TIMESTAMP
, Step_Name 				VARCHAR(100)

, Condicao 					VARCHAR(100)
, Codigo_Produto 			VARCHAR(100)
, Codigo_Produto_Derivado 	VARCHAR(100)
, Codigo_Produto_Externo 	VARCHAR(100)
, Codigo_Barras 			VARCHAR(100)
, Descricao 				VARCHAR(100)
, Data_Balanco 				VARCHAR(100)
, Empresa 					VARCHAR(100)
, Local_Estoque 			VARCHAR(100)
, Lote 						VARCHAR(100)
, Quantidade 				VARCHAR(100)
, Custo_Unitario 			VARCHAR(100)

, IDEMPRESA 				VARCHAR(100)
, IDLOCALESTOQUE 			VARCHAR(100)
, Quantidade_Tmp 			VARCHAR(100)
, Custo_Unitario_Tmp 		VARCHAR(100)
, Data_Balanco_Tmp			VARCHAR(100)
, Quantidade_Novo 			VARCHAR(100)
, Custo_Unitario_Novo 		VARCHAR(100)
, Data_Balanco_Valid 		VARCHAR(100)
, Codigo_Barras_Tmp 		VARCHAR(100)
, IDPRODUTO_Tmp 			VARCHAR(100)
, IDSUBPRODUTO_Tmp			VARCHAR(100)
, IDPRODUTO 				VARCHAR(100)		
, IDSUBPRODUTO 				VARCHAR(100)
, Observacao 				VARCHAR(100)
, IDLOTE 					VARCHAR(100)
, FLAGLOTE 					VARCHAR(100)
, DTBALANCO 				VARCHAR(100)
, IDPLANILHA 				VARCHAR(100)
, NUMSEQUENCIA 				VARCHAR(100)

, Status					VARCHAR(100)
, Error_Description 		VARCHAR(500)
)

COMMIT
